CREATE TABLE IF NOT EXISTS `admin_company_operators` (
  `operator_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'オペレータID',
  `company_id` int(11) NOT NULL COMMENT '管理組織ID',
  `role_id` int(11) NOT NULL COMMENT 'ロールID',
  `login_id` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'オペレータログインID',
  `password` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'オペレータログインパスワード',
  `operator_title` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '役職名',
  `operator_name` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'オペレータ名',
  `operator_name_kana` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'オペレータ名カナ',
  `zip1` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '郵便番号1',
  `zip2` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '郵便番号2',
  `pref` int(11) DEFAULT NULL COMMENT '都道府県',
  `address1` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '住所1',
  `address2` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '住所2',
  `free_tel1` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'フリーダイヤル1',
  `free_tel2` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'フリーダイヤル2',
  `free_tel3` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'フリーダイヤル3',
  `tel1` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '電話番号1',
  `tel2` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '電話番号2',
  `tel3` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '電話番号3',
  `fax1` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'FAX番号1',
  `fax2` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'FAX番号2',
  `fax3` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'FAX番号3',
  `url` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'サイトURL',
  `email` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'メールアドレス',
  `location` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '所在地',
  `support_limit` int(11) DEFAULT NULL COMMENT '受付可能人数',
  `description` varchar(2048) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '備考',
  `contact_name` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '受付担当者名',
  `display_flg` tinyint(1) NOT NULL DEFAULT '1' COMMENT '表示フラグ',
  `start_time` datetime DEFAULT NULL COMMENT '利用開始日時',
  `end_time` datetime DEFAULT NULL COMMENT '利用終了日時',
  `create_time` datetime NOT NULL COMMENT 'データ作成日時',
  `update_time` datetime NOT NULL COMMENT 'データ最終更新日時',
  PRIMARY KEY (`operator_id`),
  UNIQUE KEY `login_id` (`login_id`),
  KEY `company_id` (`company_id`),
  KEY `role_id` (`role_id`),
  CONSTRAINT `admin_company_operators_ibfk_1` FOREIGN KEY (`company_id`) REFERENCES `admin_companys` (`company_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `admin_company_operators_ibfk_2` FOREIGN KEY (`role_id`) REFERENCES `admin_roles` (`role_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='管理組織オペレータテーブル'